using Pkg

Pkg.add("NPZ")
Pkg.add("DelimitedFiles")
Pkg.add("GLM")
Pkg.add("NCDatasets")
Pkg.add("Plots")
Pkg.add("Statistics")
Pkg.add("DataStructures")
Pkg.add("NaNMath")
Pkg.add("LaTeXStrings")
Pkg.add("ColorSchemeTools")
Pkg.add("DataFrames")
Pkg.add("StatsBase")
Pkg.add("Revise")
Pkg.add("OhMyREPL")
Pkg.add("JuMP")
Pkg.add("DecisionTree")
Pkg.add("Images")
